<?php

use Illuminate\Database\Seeder;
use App\Models\Settings\Provincia;

class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            ['ubigeo' => '0301','nombre' =>'ABANCAY','departamento_id'=>3],
            ['ubigeo' => '0902','nombre' =>'ACOBAMBA','departamento_id'=>9],
            ['ubigeo' => '0802','nombre' =>'ACOMAYO','departamento_id'=>8],
            ['ubigeo' => '0202','nombre' =>'AIJA','departamento_id'=>2],
            ['ubigeo' => '1602','nombre' =>'ALTO AMAZONAS','departamento_id'=>16],
            ['ubigeo' => '1002','nombre' =>'AMBO','departamento_id'=>10],
            ['ubigeo' => '0302','nombre' =>'ANDAHUAYLAS','departamento_id'=>3],
            ['ubigeo' => '0903','nombre' =>'ANGARAES','departamento_id'=>9],
            ['ubigeo' => '0803','nombre' =>'ANTA','departamento_id'=>8],
            ['ubigeo' => '0303','nombre' =>'ANTABAMBA','departamento_id'=>3],
            ['ubigeo' => '0203','nombre' =>'ANTONIO RAYMONDI','departamento_id'=>2],
            ['ubigeo' => '0401','nombre' =>'AREQUIPA','departamento_id'=>4],
            ['ubigeo' => '1302','nombre' =>'ASCOPE','departamento_id'=>13],
            ['ubigeo' => '0204','nombre' =>'ASUNCION','departamento_id'=>2],
            ['ubigeo' => '2502','nombre' =>'ATALAYA','departamento_id'=>25],
            ['ubigeo' => '2002','nombre' =>'AYABACA','departamento_id'=>20],
            ['ubigeo' => '0304','nombre' =>'AYMARAES','departamento_id'=>3],
            ['ubigeo' => '2102','nombre' =>'AZANGARO','departamento_id'=>21],
            ['ubigeo' => '0102','nombre' =>'BAGUA','departamento_id'=>1],
            ['ubigeo' => '1502','nombre' =>'BARRANCA','departamento_id'=>15],
            ['ubigeo' => '2202','nombre' =>'BELLAVISTA','departamento_id'=>22],
            ['ubigeo' => '1303','nombre' =>'BOLIVAR','departamento_id'=>13],
            ['ubigeo' => '0205','nombre' =>'BOLOGNESI','departamento_id'=>2],
            ['ubigeo' => '0103','nombre' =>'BONGARA','departamento_id'=>1],
            ['ubigeo' => '0602','nombre' =>'CAJABAMBA','departamento_id'=>6],
            ['ubigeo' => '0601','nombre' =>'CAJAMARCA','departamento_id'=>6],
            ['ubigeo' => '1503','nombre' =>'CAJATAMBO','departamento_id'=>15],
            ['ubigeo' => '0804','nombre' =>'CALCA','departamento_id'=>8],
            ['ubigeo' => '0701','nombre' =>'CALLAO','departamento_id'=>7],
            ['ubigeo' => '0402','nombre' =>'CAMANA','departamento_id'=>4],
            ['ubigeo' => '0805','nombre' =>'CANAS','departamento_id'=>8],
            ['ubigeo' => '0806','nombre' =>'CANCHIS','departamento_id'=>8],
            ['ubigeo' => '2302','nombre' =>'CANDARAVE','departamento_id'=>23],
            ['ubigeo' => '1505','nombre' =>'CAÑETE','departamento_id'=>15],
            ['ubigeo' => '0502','nombre' =>'CANGALLO','departamento_id'=>5],
            ['ubigeo' => '1504','nombre' =>'CANTA','departamento_id'=>15],
            ['ubigeo' => '2103','nombre' =>'CARABAYA','departamento_id'=>21],
            ['ubigeo' => '0403','nombre' =>'CARAVELI','departamento_id'=>4],
            ['ubigeo' => '0206','nombre' =>'CARHUAZ','departamento_id'=>2],
            ['ubigeo' => '0207','nombre' =>'CARLOS FERMIN FITZCARRALD','departamento_id'=>2],
            ['ubigeo' => '0208','nombre' =>'CASMA','departamento_id'=>2],
            ['ubigeo' => '0404','nombre' =>'CASTILLA','departamento_id'=>4],
            ['ubigeo' => '0904','nombre' =>'CASTROVIRREYNA','departamento_id'=>9],
            ['ubigeo' => '0405','nombre' =>'CAYLLOMA','departamento_id'=>4],
            ['ubigeo' => '0603','nombre' =>'CELENDIN','departamento_id'=>6],
            ['ubigeo' => '0101','nombre' =>'CHACHAPOYAS','departamento_id'=>1],
            ['ubigeo' => '1203','nombre' =>'CHANCHAMAYO','departamento_id'=>12],
            ['ubigeo' => '1304','nombre' =>'CHEPEN','departamento_id'=>13],
            ['ubigeo' => '1401','nombre' =>'CHICLAYO','departamento_id'=>14],
            ['ubigeo' => '1102','nombre' =>'CHINCHA','departamento_id'=>11],
            ['ubigeo' => '0306','nombre' =>'CHINCHEROS','departamento_id'=>3],
            ['ubigeo' => '0604','nombre' =>'CHOTA','departamento_id'=>6],
            ['ubigeo' => '2104','nombre' =>'CHUCUITO','departamento_id'=>21],
            ['ubigeo' => '0807','nombre' =>'CHUMBIVILCAS','departamento_id'=>8],
            ['ubigeo' => '1209','nombre' =>'CHUPACA','departamento_id'=>12],
            ['ubigeo' => '0905','nombre' =>'CHURCAMPA','departamento_id'=>9],
            ['ubigeo' => '1202','nombre' =>'CONCEPCION','departamento_id'=>12],
            ['ubigeo' => '0406','nombre' =>'CONDESUYOS','departamento_id'=>4],
            ['ubigeo' => '0104','nombre' =>'CONDORCANQUI','departamento_id'=>1],
            ['ubigeo' => '2402','nombre' =>'CONTRALMIRANTE VILLAR','departamento_id'=>24],
            ['ubigeo' => '0605','nombre' =>'CONTUMAZA','departamento_id'=>6],
            ['ubigeo' => '2501','nombre' =>'CORONEL PORTILLO','departamento_id'=>25],
            ['ubigeo' => '0209','nombre' =>'CORONGO','departamento_id'=>2],
            ['ubigeo' => '0305','nombre' =>'COTABAMBAS','departamento_id'=>3],
            ['ubigeo' => '0801','nombre' =>'CUSCO','departamento_id'=>8],
            ['ubigeo' => '0606','nombre' =>'CUTERVO','departamento_id'=>6],
            ['ubigeo' => '1902','nombre' =>'DANIEL ALCIDES CARRION','departamento_id'=>19],
            ['ubigeo' => '1607','nombre' =>'DATEM DEL MARAÑON','departamento_id'=>16],
            ['ubigeo' => '1003','nombre' =>'DOS DE MAYO','departamento_id'=>10],
            ['ubigeo' => '2105','nombre' =>'EL COLLAO','departamento_id'=>21],
            ['ubigeo' => '2203','nombre' =>'EL DORADO','departamento_id'=>22],
            ['ubigeo' => '0808','nombre' =>'ESPINAR','departamento_id'=>8],
            ['ubigeo' => '1402','nombre' =>'FERREÑAFE','departamento_id'=>14],
            ['ubigeo' => '1802','nombre' =>'GENERAL SANCHEZ CERRO','departamento_id'=>18],
            ['ubigeo' => '1311','nombre' =>'GRAN CHIMU','departamento_id'=>13],
            ['ubigeo' => '0307','nombre' =>'GRAU','departamento_id'=>3],
            ['ubigeo' => '1004','nombre' =>'HUACAYBAMBA','departamento_id'=>10],
            ['ubigeo' => '0607','nombre' =>'HUALGAYOC','departamento_id'=>6],
            ['ubigeo' => '2204','nombre' =>'HUALLAGA','departamento_id'=>22],
            ['ubigeo' => '1005','nombre' =>'HUAMALIES','departamento_id'=>10],
            ['ubigeo' => '0501','nombre' =>'HUAMANGA','departamento_id'=>5],
            ['ubigeo' => '2003','nombre' =>'HUANCABAMBA','departamento_id'=>20],
            ['ubigeo' => '2106','nombre' =>'HUANCANE','departamento_id'=>21],
            ['ubigeo' => '0503','nombre' =>'HUANCA SANCOS','departamento_id'=>5],
            ['ubigeo' => '0901','nombre' =>'HUANCAVELICA','departamento_id'=>9],
            ['ubigeo' => '1201','nombre' =>'HUANCAYO','departamento_id'=>12],
            ['ubigeo' => '0504','nombre' =>'HUANTA','departamento_id'=>5],
            ['ubigeo' => '1001','nombre' =>'HUANUCO','departamento_id'=>10],
            ['ubigeo' => '1506','nombre' =>'HUARAL','departamento_id'=>15],
            ['ubigeo' => '0201','nombre' =>'HUARAZ','departamento_id'=>2],
            ['ubigeo' => '0210','nombre' =>'HUARI','departamento_id'=>2],
            ['ubigeo' => '0211','nombre' =>'HUARMEY','departamento_id'=>2],
            ['ubigeo' => '1507','nombre' =>'HUAROCHIRI','departamento_id'=>15],
            ['ubigeo' => '1508','nombre' =>'HUAURA','departamento_id'=>15],
            ['ubigeo' => '0212','nombre' =>'HUAYLAS','departamento_id'=>2],
            ['ubigeo' => '0906','nombre' =>'HUAYTARA','departamento_id'=>9],
            ['ubigeo' => '1101','nombre' =>'ICA','departamento_id'=>11],
            ['ubigeo' => '1803','nombre' =>'ILO','departamento_id'=>18],
            ['ubigeo' => '0407','nombre' =>'ISLAY','departamento_id'=>4],
            ['ubigeo' => '0608','nombre' =>'JAEN','departamento_id'=>6],
            ['ubigeo' => '1204','nombre' =>'JAUJA','departamento_id'=>12],
            ['ubigeo' => '2303','nombre' =>'JORGE BASADRE','departamento_id'=>23],
            ['ubigeo' => '1305','nombre' =>'JULCAN','departamento_id'=>13],
            ['ubigeo' => '1205','nombre' =>'JUNIN','departamento_id'=>12],
            ['ubigeo' => '0809','nombre' =>'LA CONVENCION','departamento_id'=>8],
            ['ubigeo' => '0505','nombre' =>'LA MAR','departamento_id'=>5],
            ['ubigeo' => '2205','nombre' =>'LAMAS','departamento_id'=>22],
            ['ubigeo' => '1403','nombre' =>'LAMBAYEQUE','departamento_id'=>14],
            ['ubigeo' => '2107','nombre' =>'LAMPA','departamento_id'=>21],
            ['ubigeo' => '0408','nombre' =>'LA UNION','departamento_id'=>4],
            ['ubigeo' => '1010','nombre' =>'LAURICOCHA','departamento_id'=>10],
            ['ubigeo' => '1006','nombre' =>'LEONCIO PRADO','departamento_id'=>10],
            ['ubigeo' => '1501','nombre' =>'LIMA','departamento_id'=>15],
            ['ubigeo' => '1603','nombre' =>'LORETO','departamento_id'=>16],
            ['ubigeo' => '0506','nombre' =>'LUCANAS','departamento_id'=>5],
            ['ubigeo' => '0105','nombre' =>'LUYA','departamento_id'=>1],
            ['ubigeo' => '1702','nombre' =>'MANU','departamento_id'=>17],
            ['ubigeo' => '1007','nombre' =>'MARAÑON','departamento_id'=>10],
            ['ubigeo' => '2206','nombre' =>'MARISCAL CACERES','departamento_id'=>22],
            ['ubigeo' => '0213','nombre' =>'MARISCAL LUZURIAGA','departamento_id'=>2],
            ['ubigeo' => '1801','nombre' =>'MARISCAL NIETO','departamento_id'=>18],
            ['ubigeo' => '1604','nombre' =>'MARISCAL RAMON CASTILLA','departamento_id'=>16],
            ['ubigeo' => '1601','nombre' =>'MAYNAS','departamento_id'=>16],
            ['ubigeo' => '2108','nombre' =>'MELGAR','departamento_id'=>21],
            ['ubigeo' => '2109','nombre' =>'MOHO','departamento_id'=>21],
            ['ubigeo' => '2004','nombre' =>'MORROPON','departamento_id'=>20],
            ['ubigeo' => '2201','nombre' =>'MOYOBAMBA','departamento_id'=>22],
            ['ubigeo' => '1103','nombre' =>'NASCA','departamento_id'=>11],
            ['ubigeo' => '0214','nombre' =>'OCROS','departamento_id'=>2],
            ['ubigeo' => '1306','nombre' =>'OTUZCO','departamento_id'=>13],
            ['ubigeo' => '1903','nombre' =>'OXAPAMPA','departamento_id'=>19],
            ['ubigeo' => '1509','nombre' =>'OYON','departamento_id'=>15],
            ['ubigeo' => '1307','nombre' =>'PACASMAYO','departamento_id'=>13],
            ['ubigeo' => '1008','nombre' =>'PACHITEA','departamento_id'=>10],
            ['ubigeo' => '2503','nombre' =>'PADRE ABAD','departamento_id'=>25],
            ['ubigeo' => '2005','nombre' =>'PAITA','departamento_id'=>20],
            ['ubigeo' => '0215','nombre' =>'PALLASCA','departamento_id'=>2],
            ['ubigeo' => '1104','nombre' =>'PALPA','departamento_id'=>11],
            ['ubigeo' => '0507','nombre' =>'PARINACOCHAS','departamento_id'=>5],
            ['ubigeo' => '0810','nombre' =>'PARURO','departamento_id'=>8],
            ['ubigeo' => '1901','nombre' =>'PASCO','departamento_id'=>19],
            ['ubigeo' => '1308','nombre' =>'PATAZ','departamento_id'=>13],
            ['ubigeo' => '0508','nombre' =>'PAUCAR DEL SARA SARA','departamento_id'=>5],
            ['ubigeo' => '0811','nombre' =>'PAUCARTAMBO','departamento_id'=>8],
            ['ubigeo' => '2207','nombre' =>'PICOTA','departamento_id'=>22],
            ['ubigeo' => '1105','nombre' =>'PISCO','departamento_id'=>11],
            ['ubigeo' => '2001','nombre' =>'PIURA','departamento_id'=>20],
            ['ubigeo' => '0216','nombre' =>'POMABAMBA','departamento_id'=>2],
            ['ubigeo' => '1009','nombre' =>'PUERTO INCA','departamento_id'=>10],
            ['ubigeo' => '2101','nombre' =>'PUNO','departamento_id'=>21],
            ['ubigeo' => '2504','nombre' =>'PURUS','departamento_id'=>25],
            ['ubigeo' => '1608','nombre' =>'PUTUMAYO','departamento_id'=>16],
            ['ubigeo' => '0812','nombre' =>'QUISPICANCHI','departamento_id'=>8],
            ['ubigeo' => '0217','nombre' =>'RECUAY','departamento_id'=>2],
            ['ubigeo' => '1605','nombre' =>'REQUENA','departamento_id'=>16],
            ['ubigeo' => '2208','nombre' =>'RIOJA','departamento_id'=>22],
            ['ubigeo' => '0106','nombre' =>'RODRIGUEZ DE MENDOZA','departamento_id'=>1],
            ['ubigeo' => '2110','nombre' =>'SAN ANTONIO DE PUTINA','departamento_id'=>21],
            ['ubigeo' => '1309','nombre' =>'SANCHEZ CARRION','departamento_id'=>13],
            ['ubigeo' => '2112','nombre' =>'SANDIA','departamento_id'=>21],
            ['ubigeo' => '0609','nombre' =>'SAN IGNACIO','departamento_id'=>6],
            ['ubigeo' => '0610','nombre' =>'SAN MARCOS','departamento_id'=>6],
            ['ubigeo' => '2209','nombre' =>'SAN MARTIN','departamento_id'=>22],
            ['ubigeo' => '0611','nombre' =>'SAN MIGUEL','departamento_id'=>6],
            ['ubigeo' => '0612','nombre' =>'SAN PABLO','departamento_id'=>6],
            ['ubigeo' => '2111','nombre' =>'SAN ROMAN','departamento_id'=>21],
            ['ubigeo' => '0218','nombre' =>'SANTA','departamento_id'=>2],
            ['ubigeo' => '0613','nombre' =>'SANTA CRUZ','departamento_id'=>6],
            ['ubigeo' => '1310','nombre' =>'SANTIAGO DE CHUCO','departamento_id'=>13],
            ['ubigeo' => '1206','nombre' =>'SATIPO','departamento_id'=>12],
            ['ubigeo' => '2008','nombre' =>'SECHURA','departamento_id'=>20],
            ['ubigeo' => '0219','nombre' =>'SIHUAS','departamento_id'=>2],
            ['ubigeo' => '0509','nombre' =>'SUCRE','departamento_id'=>5],
            ['ubigeo' => '2006','nombre' =>'SULLANA','departamento_id'=>20],
            ['ubigeo' => '2301','nombre' =>'TACNA','departamento_id'=>23],
            ['ubigeo' => '1703','nombre' =>'TAHUAMANU','departamento_id'=>17],
            ['ubigeo' => '2007','nombre' =>'TALARA','departamento_id'=>20],
            ['ubigeo' => '1701','nombre' =>'TAMBOPATA','departamento_id'=>17],
            ['ubigeo' => '2304','nombre' =>'TARATA','departamento_id'=>23],
            ['ubigeo' => '1207','nombre' =>'TARMA','departamento_id'=>12],
            ['ubigeo' => '0907','nombre' =>'TAYACAJA','departamento_id'=>9],
            ['ubigeo' => '2210','nombre' =>'TOCACHE','departamento_id'=>22],
            ['ubigeo' => '1301','nombre' =>'TRUJILLO','departamento_id'=>13],
            ['ubigeo' => '2401','nombre' =>'TUMBES','departamento_id'=>24],
            ['ubigeo' => '1606','nombre' =>'UCAYALI','departamento_id'=>16],
            ['ubigeo' => '0813','nombre' =>'URUBAMBA','departamento_id'=>8],
            ['ubigeo' => '0107','nombre' =>'UTCUBAMBA','departamento_id'=>1],
            ['ubigeo' => '0510','nombre' =>'VICTOR FAJARDO','departamento_id'=>5],
            ['ubigeo' => '0511','nombre' =>'VILCAS HUAMAN','departamento_id'=>5],
            ['ubigeo' => '1312','nombre' =>'VIRU','departamento_id'=>13],
            ['ubigeo' => '1011','nombre' =>'YAROWILCA','departamento_id'=>10],
            ['ubigeo' => '1208','nombre' =>'YAULI','departamento_id'=>12],
            ['ubigeo' => '1510','nombre' =>'YAUYOS','departamento_id'=>15],
            ['ubigeo' => '0220','nombre' =>'YUNGAY','departamento_id'=>2],
            ['ubigeo' => '2113','nombre' =>'YUNGUYO','departamento_id'=>21],
            ['ubigeo' => '2403','nombre' =>'ZARUMILLA','departamento_id'=>24],

        ];

        foreach ($items as $item)
        {
            Provincia::updateOrCreate(['nombre' => $item['nombre']], $item);
        }
    }
}
